spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liq_test
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
